import os
import tarfile
import json


def main():
    print("=" * 60)
    print("             ORBIT WARS SUBMISSION BUILDER (V10)")
    print("=" * 60)

    archive_name = "submission.tar.gz"
    single_file_name = "submission.py"

    print(f"Creating compressed archive {archive_name}...")
    files_to_include = [
        "main.py",
        "core/__init__.py",
        "core/physics.py",
        "core/observation.py",
        "strategies/__init__.py",
        "strategies/base_strategy.py",
        "strategies/elite_tactician.py",
        "profiles.json",
    ]

    with tarfile.open(archive_name, "w:gz") as tar:
        for file_path in files_to_include:
            if os.path.exists(file_path):
                tar.add(file_path)
                print(f"  + Added: {file_path}")
            else:
                print(f"  - Warning: {file_path} not found!")

    print(f"Successfully packaged {archive_name}.")

    print(f"\nCompiling standalone single-file {single_file_name}...")

    core_physics = ""
    core_obs = ""
    strat_base = ""
    strat_elite = ""

    with open("core/physics.py") as f:
        core_physics = f.read().replace("from typing", "# from typing")

    with open("core/observation.py") as f:
        core_obs = f.read().replace("from core.physics", "# from core.physics")

    with open("strategies/base_strategy.py") as f:
        strat_base = f.read()

    with open("strategies/elite_tactician.py") as f:
        strat_elite = f.read()
        strat_elite = strat_elite.replace(
            "from strategies.base_strategy import BaseStrategy", ""
        )
        strat_elite = strat_elite.replace(
            "from core.observation import ParsedObservation, Planet, Fleet", ""
        )
        strat_elite = strat_elite.replace(
            "from core.physics import distance, intersects_sun, get_planet_position_at_step, intersects_planet",
            "",
        )
        
        # Inline pre-calibrated profiles dynamically
        try:
            with open("profiles.json") as pf:
                profiles_data = json.load(pf)
            
            target_fallback_block = """        self.profiles = {
            "aggressive": {
                "hoarding_constant": 2.0,
                "evacuation_trigger": 4,
                "max_attack_dist": 80.0,
                "early_rush_limit": 8
            },
            "defensive": {
                "hoarding_constant": 28.0,
                "evacuation_trigger": 6,
                "max_attack_dist": 40.0,
                "early_rush_limit": 4
            },
            "standard": {
                "hoarding_constant": 15.0,
                "evacuation_trigger": 5,
                "max_attack_dist": 60.0,
                "early_rush_limit": 4
            }
        }"""
            
            custom_profiles_block = "        self.profiles = " + json.dumps(profiles_data, indent=12)
            strat_elite = strat_elite.replace(target_fallback_block, custom_profiles_block)
            print("Successfully inlined profiles.json into standalone agent!")
        except Exception as e:
            print(f"Warning: Failed to inline profiles.json: {e}")

    compiled_code = f"""# ==============================================================================
# Standalone Zero-Dependency Orbit Wars Submission Agent
# Generated by Antigravity AI
# ==============================================================================
import math
import time
from typing import List, Dict, Any, Union, Tuple, Set
from collections import namedtuple

# --- core/physics.py ---
{core_physics}

# --- core/observation.py ---
{core_obs}

# --- strategies/base_strategy.py ---
{strat_base}

# --- strategies/elite_tactician.py ---
{strat_elite}

# --- main.py ---
# Initialize globally to maintain state
agent_strategy = EliteTactician(
    production_weight=12.0,
    distance_weight=3.5,
    ship_cost_weight=0.1,
    comet_bonus=25.0,
    aggression_weight=1.0
)

def agent(obs) -> list:
    return agent_strategy.get_actions(obs)
"""

    with open(single_file_name, "w") as f:
        f.write(compiled_code)

    print(f"Successfully compiled standalone {single_file_name}.")
    print("=" * 60)


if __name__ == "__main__":
    main()
