# ==============================================================================
# Standalone Zero-Dependency Orbit Wars Submission Agent
# Generated by Antigravity AI
# ==============================================================================
import math
import time
from typing import List, Dict, Any, Union, Tuple, Set
from collections import namedtuple

# --- core/physics.py ---
import math
# from typing import Tuple, List, Union

CENTER = 50.0
SUN_RADIUS = 10.5
ROTATION_RADIUS_LIMIT = 50.0


def distance(p1: Tuple[float, float], p2: Tuple[float, float]) -> float:
    """Calculate Euclidean distance between two 2D points."""
    return math.sqrt((p1[0] - p2[0]) ** 2 + (p1[1] - p2[1]) ** 2)


def point_to_segment_distance(
    p: Tuple[float, float], v: Tuple[float, float], w: Tuple[float, float]
) -> float:
    """Calculate the minimum distance from point p to line segment v-w."""
    l2 = (v[0] - w[0]) ** 2 + (v[1] - w[1]) ** 2
    if l2 == 0.0:
        return distance(p, v)

    t = max(
        0.0,
        min(1.0, ((p[0] - v[0]) * (w[0] - v[0]) + (p[1] - v[1]) * (w[1] - v[1])) / l2),
    )
    projection = (v[0] + t * (w[0] - v[0]), v[1] + t * (w[1] - v[1]))
    return distance(p, projection)


def intersects_sun(
    start_x: float, start_y: float, target_x: float, target_y: float
) -> bool:
    """
    Check if a straight line trajectory from start to target intersects
    the deadly central sun at (50, 50) with radius 10.5 (safe margin).
    """
    sun_pos = (CENTER, CENTER)
    traj_distance = point_to_segment_distance(
        sun_pos, (start_x, start_y), (target_x, target_y)
    )
    return traj_distance < SUN_RADIUS


def get_planet_position_at_step(
    planet_id: int,
    step: int,
    initial_planets: List[List[Union[int, float]]],
    angular_velocity: float,
) -> Tuple[float, float]:
    """
    Calculate and forecast the exact position of a planet at a specific step in the future.
    """
    planet = next((p for p in initial_planets if p[0] == planet_id), None)
    if planet is None:
        raise ValueError(f"Planet ID {planet_id} not found in initial planets.")

    # Support both namedtuple and list
    if hasattr(planet, "x"):
        init_x, init_y, radius = planet.x, planet.y, planet.radius
    else:
        init_x, init_y, radius = planet[2], planet[3], planet[4]

    dx = init_x - CENTER
    dy = init_y - CENTER
    orbital_radius = math.sqrt(dx**2 + dy**2)

    if orbital_radius + radius < ROTATION_RADIUS_LIMIT:
        initial_angle = math.atan2(dy, dx)
        current_angle = initial_angle + angular_velocity * step
        new_x = CENTER + orbital_radius * math.cos(current_angle)
        new_y = CENTER + orbital_radius * math.sin(current_angle)
        return (new_x, new_y)

    return (init_x, init_y)


def intersects_planet(
    start_x: float,
    start_y: float,
    target_x: float,
    target_y: float,
    obstacle_id: int,
    initial_planets: List[List[Union[int, float]]],
    angular_velocity: float,
    start_step: int,
    travel_turns: int,
) -> bool:
    """
    Check if a straight line trajectory from start to target intersects
    with a moving or static intermediate planet during the travel period.
    """
    # Sample collision at the start, middle, and end steps of the travel period
    steps_to_check = [start_step, start_step + travel_turns // 2, start_step + travel_turns]

    # Get radius of the obstacle
    planet = next((p for p in initial_planets if p[0] == obstacle_id), None)
    if planet is None:
        return False

    # Support both namedtuple and list
    if hasattr(planet, "radius"):
        radius = planet.radius
    else:
        radius = planet[4]

    for step in steps_to_check:
        try:
            obs_pos = get_planet_position_at_step(
                obstacle_id, step, initial_planets, angular_velocity
            )
        except ValueError:
            continue

        dist = point_to_segment_distance(
            obs_pos, (start_x, start_y), (target_x, target_y)
        )
        if dist < radius + 0.2:
            return True

    return False


# --- core/observation.py ---
from typing import List, Dict, Any, Union, Set
from collections import namedtuple

Planet = namedtuple(
    "Planet", ["id", "owner", "x", "y", "radius", "ships", "production"]
)
Fleet = namedtuple(
    "Fleet", ["id", "owner", "x", "y", "angle", "from_planet_id", "ships"]
)


class ParsedObservation:
    """
    Parses and transforms raw game observations from the Kaggle environment
    into clean, structured, and easy-to-use domain objects.
    """

    def __init__(self, obs: Union[Dict[str, Any], Any]):
        def get_val(key: str, default: Any = None) -> Any:
            if isinstance(obs, dict):
                return obs.get(key, default)
            return getattr(obs, key, default)

        self.player: int = int(get_val("player", 0))
        self.step: int = int(get_val("step", 0))
        self.angular_velocity: float = float(get_val("angular_velocity", 0.0))
        self.remaining_overage_time: float = float(
            get_val("remainingOverageTime", 60.0)
        )

        raw_initial = get_val("initial_planets", [])
        self.initial_planets: List[Planet] = [Planet(*p) for p in raw_initial]
        self.initial_planets_dict: Dict[int, Planet] = {
            p.id: p for p in self.initial_planets
        }

        self.comet_planet_ids: Set[int] = set(get_val("comet_planet_ids", []))
        self.raw_comets: List[Dict[str, Any]] = get_val("comets", [])

        self.exiting_comet_ids: Set[int] = set()
        for group in self.raw_comets:
            path_index = group.get("path_index", -1)
            planet_ids = group.get("planet_ids", [])
            paths = group.get("paths", [])

            for i, pid in enumerate(planet_ids):
                if i < len(paths):
                    path = paths[i]
                    if len(path) - path_index <= 2:
                        self.exiting_comet_ids.add(pid)

        raw_planets = get_val("planets", [])
        self.all_planets: Dict[int, Planet] = {}
        self.my_planets: List[Planet] = []
        self.enemy_planets: List[Planet] = []
        self.neutral_planets: List[Planet] = []
        self.active_comets: List[Planet] = []

        for p_list in raw_planets:
            p = Planet(*p_list)
            self.all_planets[p.id] = p

            if p.id in self.comet_planet_ids:
                if p.id not in self.exiting_comet_ids:
                    self.active_comets.append(p)

            if p.owner == self.player:
                self.my_planets.append(p)
            elif p.owner == -1:
                self.neutral_planets.append(p)
            else:
                self.enemy_planets.append(p)

        raw_fleets = get_val("fleets", [])
        self.all_fleets: List[Fleet] = [Fleet(*f) for f in raw_fleets]
        self.my_fleets: List[Fleet] = [
            f for f in self.all_fleets if f.owner == self.player
        ]
        self.enemy_fleets: List[Fleet] = [
            f for f in self.all_fleets if f.owner != self.player
        ]


# --- strategies/base_strategy.py ---
from typing import List, Dict, Any, Union


class BaseStrategy:
    """
    Abstract base class for all Orbit Wars agent strategies.
    Ensures that any strategy implements get_actions method with proper types.
    """

    def get_actions(
        self, observation: Union[Dict[str, Any], Any]
    ) -> List[List[Union[int, float]]]:
        """
        Calculate and return actions for this step.

        Args:
            observation (Union[Dict[str, Any], Any]): Raw observation from the environment.

        Returns:
            List[List[Union[int, float]]]: List of moves, where each move is:
                                          [from_planet_id, direction_angle_rad, num_ships]
        """
        raise NotImplementedError("Strategies must implement the get_actions method.")


# --- strategies/heuristic_scorer.py ---
import math
from typing import List, Dict, Any, Union, Tuple





class HeuristicScorer(BaseStrategy):
    """
    Refined High-Performance Heuristic Scorer strategy for Orbit Wars.
    Integrates Outgoing Fleet Lock to prevent spamming, high-proximity targeting,
    and high concentration of launch force.
    """

    def __init__(
        self,
        production_weight: float = 12.0,
        distance_weight: float = 3.5,
        ship_cost_weight: float = 0.1,
        comet_bonus: float = 25.0,
        aggression_weight: float = 1.0,
    ):
        self.production_weight = production_weight
        self.distance_weight = distance_weight
        self.ship_cost_weight = ship_cost_weight
        self.comet_bonus = comet_bonus
        self.aggression_weight = aggression_weight

    def estimate_fleet_speed(self, num_ships: int) -> float:
        """
        Estimate fleet speed based on the official Kaggle Orbit Wars formula.
        """
        max_speed = 6.0
        if num_ships <= 1:
            return 1.0

        log_ratio = math.log(num_ships) / math.log(1000.0)
        speed = 1.0 + 5.0 * max(0.0, log_ratio) ** 1.5
        return min(speed, max_speed)

    def estimate_fleet_target(self, fleet: Fleet, planets: List[Planet]) -> Union[Planet, None]:
        """
        Estimate the target planet of a flying fleet using high-precision physical ray-casting.
        """
        best_planet = None
        min_dist_to_line = float("inf")

        dx = math.cos(fleet.angle)
        dy = math.sin(fleet.angle)

        for p in planets:
            if p.id == fleet.from_planet_id:
                continue
            v_x = p.x - fleet.x
            v_y = p.y - fleet.y

            proj = v_x * dx + v_y * dy
            if proj < 0:
                continue

            closest_x = fleet.x + proj * dx
            closest_y = fleet.y + proj * dy

            dist_to_ray = math.sqrt((p.x - closest_x)**2 + (p.y - closest_y)**2)

            if dist_to_ray <= p.radius + 3.0:
                dist_to_p = math.sqrt(v_x**2 + v_y**2)
                if dist_to_p < min_dist_to_line:
                    min_dist_to_line = dist_to_p
                    best_planet = p

        return best_planet

    def get_actions(
        self, observation: Union[Dict[str, Any], Any]
    ) -> List[List[Union[int, float]]]:
        obs = ParsedObservation(observation)
        moves: List[List[Union[int, float]]] = []

        planet_ships = {p.id: p.ships for p in obs.my_planets}

        self.sent_fleets_tracker = getattr(self, "sent_fleets_tracker", {})
        self.sent_fleets_tracker = {pid: arr_step for pid, arr_step in self.sent_fleets_tracker.items() if obs.step < arr_step}

        # Threat scanning (Anti-Snipe Defense Shield)
        threats: Dict[int, List[Tuple[Fleet, int]]] = {}
        for fleet in obs.all_fleets:
            if fleet.owner == obs.player:
                continue
            target_planet = self.estimate_fleet_target(fleet, list(obs.all_planets.values()))
            if target_planet and target_planet.owner == obs.player:
                dist = distance((fleet.x, fleet.y), (target_planet.x, target_planet.y))
                speed = self.estimate_fleet_speed(fleet.ships)
                arr_step = obs.step + int(math.ceil(dist / speed))
                if target_planet.id not in threats:
                    threats[target_planet.id] = []
                threats[target_planet.id].append((fleet, arr_step))

        defenses_needed: Dict[int, int] = {}
        for my_p_id, fleet_list in threats.items():
            my_p = obs.all_planets[my_p_id]
            fleet_list.sort(key=lambda x: x[1])

            current_garrison = my_p.ships
            last_step = obs.step
            total_deficit = 0

            for fleet, arr_step in fleet_list:
                turns = arr_step - last_step
                current_garrison += turns * my_p.production
                last_step = arr_step

                if fleet.ships >= current_garrison:
                    deficit = fleet.ships - current_garrison + 2
                    total_deficit += deficit
                    current_garrison = 2
                else:
                    current_garrison -= fleet.ships

            if total_deficit > 0:
                defenses_needed[my_p_id] = total_deficit

        # Scan for vulturing candidates
        vulturing_targets: Dict[int, int] = {}
        for fleet in obs.all_fleets:
            if fleet.owner == obs.player:
                continue
            target_planet = self.estimate_fleet_target(fleet, list(obs.all_planets.values()))
            if target_planet and target_planet.owner != obs.player:
                dist = distance((fleet.x, fleet.y), (target_planet.x, target_planet.y))
                speed = self.estimate_fleet_speed(fleet.ships)
                arr_step = obs.step + int(math.ceil(dist / speed))
                vulturing_targets[target_planet.id] = arr_step

        candidate_targets: List[Planet] = []
        candidate_targets.extend(obs.enemy_planets)
        candidate_targets.extend(obs.neutral_planets)
        candidate_targets.extend(obs.active_comets)

        # Add threatened allied planets to candidates
        for p in obs.my_planets:
            if p.id in defenses_needed:
                candidate_targets.append(p)

        if not candidate_targets or not obs.my_planets:
            return moves

        owners = {p.owner for p in obs.my_planets + obs.enemy_planets if p.owner != -1}
        is_four_player = len(owners) > 2

        for mine in obs.my_planets:
            best_target: Planet = None
            best_score: float = -float("inf")
            best_ships_to_send: int = 0
            best_angle: float = 0.0
            best_travel_turns: int = 0

            available_ships = planet_ships.get(mine.id, 0)

            if len(obs.my_planets) <= 1:
                min_reserve_ships = 5
            elif obs.step < 100 and len(obs.my_planets) <= 2:
                min_reserve_ships = 12 if not is_four_player else 20
            else:
                min_reserve_ships = 22 if not is_four_player else 35

            min_reserve_ships = min(min_reserve_ships, int(available_ships * 0.4))
            min_reserve_ships = max(5 if len(obs.my_planets) <= 1 else 10, min_reserve_ships)
            if available_ships < min_reserve_ships:
                continue

            for target in candidate_targets:
                if target.id == mine.id:
                    continue
                if target.id in self.sent_fleets_tracker:
                    continue
                curr_dist = distance((mine.x, mine.y), (target.x, target.y))
                if curr_dist <= 0:
                    continue

                max_attack_dist = 55.0
                if obs.step < 100 and len(obs.my_planets) <= 2:
                    max_attack_dist = 35.0

                if curr_dist > max_attack_dist and target.owner != obs.player:
                    continue

                is_defense = (target.owner == obs.player)
                is_vulturing = (target.id in vulturing_targets)

                if is_defense:
                    needed = defenses_needed.get(target.id, 5)
                    proposed_ships = needed
                    if available_ships - proposed_ships < min_reserve_ships:
                        proposed_ships = available_ships - min_reserve_ships
                    if proposed_ships <= 0:
                        continue
                else:
                    proposed_ships = max(target.ships + 2, int(available_ships * 0.75))
                    proposed_ships = min(proposed_ships, available_ships - 5)

                    if proposed_ships <= target.ships:
                        continue

                est_speed = self.estimate_fleet_speed(proposed_ships)

                best_t = None
                min_diff = float("inf")
                best_pred_pos = None

                for t in range(1, 80):
                    arrival_step = obs.step + t
                    try:
                        pred_pos = get_planet_position_at_step(
                            target.id,
                            arrival_step,
                            obs.initial_planets,
                            obs.angular_velocity,
                        )
                    except ValueError:
                        pred_pos = (target.x, target.y)

                    dist = distance((mine.x, mine.y), pred_pos)
                    travel_turns = dist / est_speed
                    diff = abs(travel_turns - t)
                    if diff < min_diff:
                        min_diff = diff
                        best_t = t
                        best_pred_pos = pred_pos

                predicted_pos = best_pred_pos
                travel_turns = max(1, int(math.ceil(distance((mine.x, mine.y), predicted_pos) / est_speed)))

                if intersects_sun(mine.x, mine.y, predicted_pos[0], predicted_pos[1]):
                    continue

                obstacle_collision = False
                for other_p in obs.all_planets.values():
                    if other_p.id == mine.id or other_p.id == target.id:
                        continue
                    if intersects_planet(
                        mine.x,
                        mine.y,
                        predicted_pos[0],
                        predicted_pos[1],
                        other_p.id,
                        obs.initial_planets,
                        obs.angular_velocity,
                        obs.step,
                        travel_turns,
                    ):
                        obstacle_collision = True
                        break

                if obstacle_collision:
                    continue

                pred_dist = distance((mine.x, mine.y), predicted_pos)
                angle = math.atan2(predicted_pos[1] - mine.y, predicted_pos[0] - mine.x)

                if is_defense:
                    ships_needed = proposed_ships
                else:
                    if target.owner == -1 or target.id in obs.comet_planet_ids:
                        predicted_garrison = target.ships
                    else:
                        predicted_garrison = target.ships + travel_turns * target.production

                    ships_needed = predicted_garrison + 2

                    if proposed_ships < ships_needed:
                        proposed_ships = ships_needed

                    if available_ships < proposed_ships + 5:
                        continue

                # Dynamic ROI formula
                enemy_multiplier = 2.0 if target.owner != -1 and not is_defense else 1.0
                econ_value = target.production * enemy_multiplier
                efficiency = econ_value / max(1, proposed_ships)

                score = (
                    self.production_weight * econ_value * (0.3 + 0.7 * efficiency)
                    - self.distance_weight * pred_dist
                )

                if is_vulturing:
                    score += 45.0

                if target.id in obs.comet_planet_ids:
                    score += self.comet_bonus

                if is_defense:
                    score = 250.0 + target.production * 15.0 - pred_dist * 2.0

                score *= self.aggression_weight

                if score > best_score:
                    best_score = score
                    best_target = target
                    best_ships_to_send = proposed_ships
                    best_angle = angle
                    best_travel_turns = travel_turns

            if best_target is not None and best_ships_to_send > 0:
                moves.append([mine.id, best_angle, best_ships_to_send])
                planet_ships[mine.id] -= best_ships_to_send
                self.sent_fleets_tracker[best_target.id] = obs.step + best_travel_turns

        return moves


# --- main.py ---
# Initialize globally to maintain state
agent_strategy = HeuristicScorer(
    production_weight=15.0,
    distance_weight=0.7,
    ship_cost_weight=0.1,
    comet_bonus=25.0,
    aggression_weight=1.5
)

def agent(obs) -> list:
    return agent_strategy.get_actions(obs)
